-- CRIAÇÃO TABELAS | DDL
-- DATA DEFINITION LANGUAGE

CREATE TABLE Pessoa(Id INT IDENTITY(1,1), Nome VARCHAR(100), Idade INT);

-- CRIANDO UMA PRIMARY KEY VIA ALTER TABLE
-- CONSTRAINT É USADO PARA CRIAR PK, KF E UNIQUE

ALTER TABLE Pessoa ADD CONSTRAINT PK_Pessoa PRIMARY KEY(Id);

-- ADICIONANDO UMA NOVA COLUNA À TABELA

ALTER TABLE Pessoa ADD RG VARCHAR(15);

-- ALTERANDO A IDADE PARA NOT NULL 

ALTER TABLE Pessoa ALTER COLUMN Idade INT NOT NULL;

-- DELETANDO UMA TABELA

DROP TABLE Pessoa

-- CRIANDO A TABELA CORRETAMENTE

CREATE TABLE Pessoa(Id INT IDENTITY(1,1) PRIMARY KEY, Nome VARCHAR(100), Idade INT NOT NULL, RG VARCHAR(15));

-- SEGUNDA TABELA QUE RELACIONA COM PESSOA

CREATE TABLE Endereço(Id INT IDENTITY(1,1) PRIMARY KEY, Cidade VARCHAR(50) NOT NULL, Rua VARCHAR(50) NOT NULL, Numero INT NOT NULL, Id_Pessoa INT FOREIGN KEY REFERENCES Pessoa(Id));

-- CRIANDO TABELA 1:1 - Id_Pessoa INT UNIQUE FOREIGN KEY REFERENCES Pessoa(Id)

-- PRIMARY KEY COMPOSTA - Id INT IDENTITY(1,1) PRIMARY KEY (Id, Nome, Numero)

DROP TABLE Endereço
DROP TABLE Pessoa

-- EXERCÍCIO (1:N)

CREATE TABLE Pessoa(Id INT IDENTITY(1,1) PRIMARY KEY, Nome VARCHAR(100));
CREATE TABLE Emprego(Id INT IDENTITY(1,1) PRIMARY KEY, NomeDaEmpresa VARCHAR(100) NOT NULL, Cargo VARCHAR(50) NOT NULL, Id_Pessoa INT FOREIGN KEY REFERENCES Pessoa(Id));
