CREATE TABLE Pessoa
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome VARCHAR(50) NOT NULL,
);

CREATE TABLE Emprego
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Nome_Empresa VARCHAR(50) NOT NULL,
	Cargo VARCHAR(50) NOT NULL,
	Pessoa_Id INT FOREIGN KEY REFERENCES Pessoa(Id),
);